version: '3.8'

services:
  flash_cards_api_dev:
    container_name: flash_cards_api_dev
    image: flash_cards_api_dev:1.0.0
    build:
      context: .
      target: development
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev
    restart: unless-stopped

networks:
  default:
    driver: bridge